all:demo1 demo2 demo3 demo4 demo5 demo6 demo7 demo8 demo9 demo10
demo1:demo1.cpp
	g++ -g -o demo1 demo1.cpp -lpthread

demo2:demo2.cpp
	g++ -g -o demo2 demo2.cpp -lpthread

demo3:demo3.cpp
	g++ -g -o demo3 demo3.cpp -lpthread

demo4:demo4.cpp
	g++ -g -o demo4 demo4.cpp -lpthread

demo5:demo5.cpp
	g++ -g -o demo5 demo5.cpp -lpthread

demo6:demo6.cpp
	g++ -g -o demo6 demo6.cpp -lpthread

demo7:demo7.cpp
	g++ -g -o demo7 demo7.cpp -lpthread

demo8:demo8.cpp
	g++ -g -o demo8 demo8.cpp -lpthread

demo9:demo9.cpp
	g++ -g -o demo9 demo9.cpp -lpthread

demo10:demo10.cpp
	g++ -g -o demo10 demo10.cpp -lpthread

clean:
	rm -f demo1 demo2 demo3 demo4 demo5 demo6 demo7 demo8 demo9
	rm -f demo10
