all:demo01 demo02 demo03 demo04 demo05 demo06 demo07 demo08 demo10 demo11 demo12\
    demo13 demo31 demo32 demo33 demo20 demo26 demo27\
    book10 book2 tcpselect client tcppoll tcpepoll tcpepoll1 client1

demo01:demo01.cpp
	g++ -g -o demo01 demo01.cpp -lm -lc -lpthread

demo02:demo02.cpp
	g++ -g -o demo02 demo02.cpp -lm -lc -lpthread

demo03:demo03.cpp
	g++ -g -o demo03 demo03.cpp -lm -lc -lpthread

demo04:demo04.cpp
	g++ -g -o demo04 demo04.cpp -lm -lc -lpthread

demo05:demo05.cpp
	g++ -g -o demo05 demo05.cpp ../_public.cpp -lm -lc -lpthread 

demo06:demo06.cpp
	g++ -g -o demo06 demo06.cpp ../_public.cpp -lm -lc -lpthread 

demo07:demo07.cpp
	g++ -g -o demo07 demo07.cpp ../_public.cpp -lm -lc -lpthread

demo08:demo08.cpp
	g++ -g -o demo08 demo08.cpp ../_public.cpp -lm -lc -lpthread

demo10:demo10.cpp
	g++ -g -o demo10 demo10.cpp ../_public.cpp -lm -lc -lpthread

demo11:demo11.cpp
	g++ -g -o demo11 demo11.cpp ../_public.cpp -lm -lc -lpthread

demo12:demo12.cpp
	g++ -g -o demo12 demo12.cpp ../_public.cpp -lm -lc -lpthread

demo13:demo13.cpp
	g++ -g -o demo13 demo13.cpp ../_public.cpp -lm -lc -lpthread

demo14:demo14.cpp
	g++ -g -o demo14 demo14.cpp ../_public.cpp -lm -lc -lpthread

demo31:demo31.cpp
	g++ -g -o demo31 demo31.cpp ../_public.cpp -lm -lc -lpthread

demo32:demo32.cpp
	g++ -g -o demo32 demo32.cpp ../_public.cpp -lm -lc -lpthread

demo33:demo33.cpp
	g++ -g -o demo33 demo33.cpp ../_public.cpp -lm -lc -lpthread

demo20:demo20.cpp
	g++ -g -o demo20 demo20.cpp ../_public.cpp -lpthread -lm -lc -lpthread

demo26:demo26.cpp
	g++ -g -o demo26 demo26.cpp ../_public.cpp -lm -lc -lpthread

demo27:demo27.cpp
	g++ -g -o demo27 demo27.cpp ../_public.cpp -lm -lc -lpthread

book10:book10.cpp
	g++ -g -o book10 book10.cpp ../_public.cpp -lm -lc -lpthread 

book2:book2.cpp
	g++ -g -o book2 book2.cpp ../_public.cpp -lm -lc -lpthread 

tcpselect:tcpselect.cpp
	g++ -g -o tcpselect tcpselect.cpp   

tcppoll:tcppoll.cpp
	g++ -g -o tcppoll tcppoll.cpp   

tcpepoll:tcpepoll.cpp
	g++ -g -o tcpepoll tcpepoll.cpp   

tcpepoll1:tcpepoll1.cpp
	g++ -g -o tcpepoll1 tcpepoll1.cpp   

client:client.cpp
	g++ -g -o client client.cpp   

client1:client1.cpp
	g++ -g -o client1 client1.cpp   

clean:
	rm demo01 demo02 demo03 demo04 demo05 demo06 demo07 demo08 demo10 demo11 demo12
	rm demo13 demo14 demo31 demo32 demo33 demo20 demo26 demo27
	rm book10 book2 tcpselect client tcppoll tcpepoll tcpepoll1 client1
